<?PHP
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2009 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN DSls_DailySales
 */


class DSls_DailySales_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'DSls_DailySales';
	var $object_name = 'DSls_DailySales';
	var $table_name = 'dsls_dailysales';
	var $importable = false;

	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO

		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $custid;
		var $custtype;
		var $region;
		var $loc;
		var $slsm;
		var $todays_orders;
		var $currency_id;
		var $pending_orders;
		var $todays_credits;
		var $pending_credits;
		var $mtd_projected;
		var $ytd_projected;
		var $mtd_sales;
		var $mtd_gp;
		var $mtd_frt;
		var $mtd_cores;
		var $ytd_sales;
		var $ytd_gp;
		var $ly_sales;
		var $ly_gp;
		var $mtd_projected_noem;
		var $ytd_projected_noem;
		var $mtd_budget_sales;
		var $mtd_budget_gp;
		var $mtd_budget_noem_sales;
		var $mtd_budget_noem_gp;
		var $ytd_budget_sales;
		var $ytd_budget_gp;
		var $ytd_budget_noem_sales;
		var $ytd_budget_noem_gp;
		var $lytd_sales;
		var $mtd_projected_undercar;
		var $mtd_budget_undercar_sales;
		var $mtd_budget_undercar_gp;
		var $ytd_projected_undercar;
		var $ytd_budget_undercar_sales;
		var $ytd_budget_undercar_gp;
		var $mly_sls;
		var $mtd_sls_noem;
		var $mtd_gp_noem;
		var $ytd_sls_noem;
		var $ytd_gp_noem;
		var $ly_sls_noem;
		var $ly_gp_noem;
		var $mtd_sls_undercar;
		var $mtd_gp_undercar;
		var $ytd_sls_undercar;
		var $ytd_gp_undercar;
		var $ly_sls_undercar;
		var $ly_gp_undercar;
		var $lm_sales;
		var $lm_gp;
		var $lytm_sales;
		var $lytm_gp;
		var $ytd_projected_gp;
		var $lytd_gp;
	




	function DSls_DailySales_sugar(){	
		parent::Basic();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>